## Persistindo Objetos em Disco ##

#### Importando as bibliotecas necessárias

In [2]:
import pickle
import joblib
import numpy as np
import _pickle as cPickle

#### Criação do objeto do tipo lista.

In [3]:
lista = [1500,1234,567,14]

#### Criação do arquivo em disco.

In [4]:
arquivo = open('lista.pkl','wb')

#### Persistindo o objeto em disco.

In [5]:
pickle.dump(lista,arquivo)

In [6]:
arquivo.close()

In [7]:
!ls

'ls' is not recognized as an internal or external command,
operable program or batch file.


#### Carregando o objeto a partir do disco para a memória.

In [8]:
arquivo2 = open('lista.pkl','rb')

In [9]:
lista2 = pickle.load(arquivo2)

In [10]:
arquivo2.close()

In [11]:
lista2

[1500, 1234, 567, 14]

## Persistindo objetos utilizando o Numpy

#### Definindo o array

In [12]:
x = np.arange(10)

In [13]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Persistindo o array em disco

In [14]:
np.save('array', x)

#### Listando os arquivos em disco

In [15]:
!ls

'ls' is not recognized as an internal or external command,
operable program or batch file.


#### Carregando o objeto a partir do disco para a memória.

In [17]:
x2 = np.load('array.npy')

In [18]:
x2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Persistindo a lista criada anteriormente em disco

In [19]:
np.save('lista2.npy',lista2)

#### Carregando o objeto a partir do disco para a memória.

In [20]:
lista3 = np.load('lista2.npy')

In [21]:
lista3

array([1500, 1234,  567,   14])

#### Verificando o tipo do objeto criado.

In [22]:
type(lista3)

numpy.ndarray

## Persistindo objetos utilizando o Joblib

#### Persistindo a lista criada anteriormente em disco.

In [23]:
joblib.dump(lista3,'lista3.joblib')

['lista3.joblib']

#### Listando os arquivos em disco

In [24]:
!ls

'ls' is not recognized as an internal or external command,
operable program or batch file.


#### Persistindo a lista criada anteriormente em disco utilizando compressão.

In [25]:
joblib.dump(lista3,'lista3.gz',compress=True)

['lista3.gz']

#### Carregando o objeto a partir do disco para a memória.

In [26]:
lista4 = joblib.load('lista3.gz')

In [27]:
lista4

array([1500, 1234,  567,   14])