# Python para Análise de Dados - Numpy   

<p> Iremos aprender a trabalhar coma biblioteca Numpy.


# Acessando Dimensões no Array

In [1]:
# Importando o Numpy
import numpy as np

In [2]:
# Gera um array aleatório de 10 linhas e 2 colunas
# formato linha,coluna
my_array = np.random.random([10,2])

In [3]:
my_array

array([[0.80536071, 0.52495405],
       [0.50922571, 0.93567291],
       [0.01343775, 0.62885916],
       [0.98900285, 0.70271692],
       [0.56987838, 0.12338078],
       [0.33930159, 0.05630562],
       [0.53797011, 0.3795248 ],
       [0.95483901, 0.33058874],
       [0.71218537, 0.45229924],
       [0.3397022 , 0.81329337]])

In [4]:
# Imprimindo o primeiro elemento (1 linha)
my_array[0]

array([0.80536071, 0.52495405])

In [5]:
# Imprimindo o primeiro elemento da coluna 0 (1 coluna)
my_array[0][0]

0.8053607123893051

In [6]:
# Primeiro elemento da coluna 1
my_array[0][1]

0.5249540493911982

In [7]:
# Segundo elemento da coluna 1
my_array[1][1]

0.935672914722663

In [8]:
# Segundo elemento da coluna escrito com virgula.
# O primeiro valor especifica a linha e o segundo valor especifica a coluna.
my_array[1,1]

0.935672914722663

In [9]:
# Imprimindo até 3 valores da coluna 1
my_array[:3,1]

array([0.52495405, 0.93567291, 0.62885916])

In [10]:
# Imprime todas as linhas da coluna 2 * 10
my_array[:,1] * 10

array([5.24954049, 9.35672915, 6.28859155, 7.02716915, 1.23380779,
       0.56305616, 3.79524797, 3.3058874 , 4.5229924 , 8.13293371])

In [11]:
# Comparação retorna indices
my_array > 0.50

array([[ True,  True],
       [ True,  True],
       [False,  True],
       [ True,  True],
       [ True, False],
       [False, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [False,  True]])

In [12]:
# Acessando valores por índices
my_array[my_array > 0.50]

array([0.80536071, 0.52495405, 0.50922571, 0.93567291, 0.62885916,
       0.98900285, 0.70271692, 0.56987838, 0.53797011, 0.95483901,
       0.71218537, 0.81329337])

# Carregar Arrays NumPy a partir de arquivos de Texto

In [13]:
import numpy as np

In [14]:
# Lendo um arquivo do tipo .txt
dataset = np.loadtxt('dataset_array.txt', delimiter=',')

In [15]:
dataset.shape

(6,)

In [16]:
dataset

array([1., 2., 3., 4., 5., 6.])

In [17]:
# carregando um arquivo dividido em 3 arrays
a, b, c = np.loadtxt('dataset_valores.txt', skiprows=1, unpack=True )

In [18]:
# Array a
a

array([0.4839, 0.1292, 0.1781, 0.7676, 0.5993])

In [19]:
# Array B
b

array([0.4536, 0.6875, 0.3049, 0.5801, 0.4357])

In [20]:
# Array C
c

array([0.3561, 0.6565, 0.8928, 0.2038, 0.741 ])

In [21]:
# Carrega o arquivo ignorando as 2 primeiras linhas e preenchendo os valores vazio por 0
# Obs: os valores string também são convertidos!!

dataset = np.genfromtxt('dataset_valores_vazio.txt', skip_header=2, filling_values=0)

In [22]:
# Imprimindo o dataset
dataset

array([[0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875, 0.    ],
       [0.1781, 0.3049, 0.8928],
       [0.    , 0.5801, 0.2038],
       [0.5993, 0.4357, 0.741 ]])